name: Prettier Enforcement

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.0
        with:
          prettier_options: --write **/*.{js,ts,tsx,scss}
          only_changed: false
          dry: false
